### ISSUE TITLE
Doesn't Work with Tomcat 9 (Tested with Tomcat 9.0.12)

### ISSUE THREAD

**Issue by KrishnaST** [neykov/extract-ssl-secrets#1]

**Comment by neykov** [comment]
Thanks for reporting @KrishnaST. Might be java version related - can you give some details on what java version and which tomcat connector you are using.

**Comment by neykov** [comment]
I was able to reproduce this and tracked it down to the usage of TLS 1.3. It's currently not supported. I'll look into adding support for it.

**Comment by neykov** [comment]
TLS 1.3 support is available in the [extract-ssl-secrets-3.0.0.jar](https://repo1.maven.org/maven2/name/neykov/extract-ssl-secrets/3.0.0/extract-ssl-secrets-3.0.0.jar) release.
