### ISSUE TITLE
How to deattach?

### ISSUE THREAD

**Issue by thomasoliw** [neykov/extract-ssl-secrets#11]
Hello,

I can successfully attach to my running Java application and I get a steady stream of session keys in the logfile.
Tracing and decrypting packages works fine, so the main goal achieved.
But how do I de-attach? I could not find a running java pid for extract-tls-secrets to kill and I do not want to leave the key logging enabled.
I am probably missing something obvious.. new to this.. :-)

Best Regards, 
Thomas

**Comment by neykov** [comment]
@thomasoliw You can restart the target process to stop the logging.

**Comment by neykov** [comment]
Detaching from a running process is now available in the [5.0.0 release](https://github.com/neykov/extract-tls-secrets/releases/tag/v5.0.0).
