### ISSUE TITLE
can't see the  TLS response of request

### ISSUE THREAD

**Issue by yili001** [neykov/extract-ssl-secrets#13]
Hi, thanks for providing this tool, after following the steps in README, I successfully configured the connection between Wireshark and my java-httpclient demo, and now Wireshark captured the TLS request sent in httpClient(the test https link is https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie), but I can't see the TLS response of this request, Is this because of my Wireshark filter setting, or need extra configuration?
The Wirshark screenshot:
![image](https://user-images.githubusercontent.com/42227265/177002882-231d7edc-5c67-4c5f-aa6e-261eacef2665.png)

**Comment by neykov** [comment]
The reason is your filter settings. You can right click and [Follow stream](https://www.wireshark.org/docs/wsug_html_chunked/ChAdvFollowStreamSection.html) to see the full communication for the particular request.

**Comment by yili001** [comment]
Thanks for the tip,I will give it a try.

**Comment by yili001** [comment]
Indeed, after change the filter setting to `(http || tls) and (tcp.port==8081 || tcp.port==443)`,I can see the TLS traffic sent by HttpClient in my spring boot application which listens on port 8081.
![image](https://user-images.githubusercontent.com/42227265/178085827-21a18322-f078-40df-8653-85438073cff0.png)
