### ISSUE TITLE
EXPORTER_SECRET not work

### ISSUE THREAD

**Issue by ofloxacin** [neykov/extract-ssl-secrets#16]
EXPORTER_SECRET not logged, thanks

![image](https://user-images.githubusercontent.com/9795941/207277014-71011507-e7b2-4242-a178-f71359aeae31.png)

**Comment by neykov** [comment]
Thank you for the report @ofloxacin . I'll investigate.
Is the missing log preventing you from decrypting traffic?

**Comment by raboof** [comment]
I'm also only seeing `CLIENT_HANDSHAKE_TRAFFIC_SECRET` and `CLIENT_TRAFFIC_SECRET_0` lines, and wireshark isn't decrypting the traffic - perhaps because this is a TLSv1.3 connection?

**Comment by raboof** [comment]
I'm using https://hc.apache.org/httpcomponents-client-5.2.x as a HTTP client, tested with:
```
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (build 1.8.0_362-ga)
OpenJDK 64-Bit Server VM (build 25.362-bga, mixed mode)
```
and
```
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+0-adhoc..source)
OpenJDK 64-Bit Server VM (build 11.0.18+0-adhoc..source, mixed mode)
```

It seems `onKeyDerivation` is only called for keys of types `TlsServerHandshakeTrafficSecret`, `TlsClientHandshakeTrafficSecret`, `TlsServerAppTrafficSecret` and `TlsClientAppTrafficSecret`.

**Comment by neykov** [comment]
@raboof can you runt he client with `-Djavax.net.debug=all` and share the output. I'm mostly interested in what types of ciphers are used for the connection.
TLS1.3 is covered by the tests, so that's not the reason - should be something more specific to your environment.

**Comment by raboof** [comment]
Sure: 
[verbose-out.txt](https://github.com/neykov/extract-tls-secrets/files/10931384/verbose-out.txt)

**Comment by neykov** [comment]
@raboof I tried to reproduce the same set up on my end. I configured TLSv1.3 with same cipher (`TLS_AES_256_GCM_SHA384`). Here are the secrets that get logged (from the client):

```
SERVER_HANDSHAKE_TRAFFIC_SECRET 6728FCF33C0A58B444672050ADD6EE37372314E521A8648B9982C253F66EC234 150C3BB8C112AA0A0031D41FFD73A7986F9DD5C7F8EE84B8579BA5E05E177ADF2659C2E1E5E7B4F5486CC8B32B34DE18
CLIENT_HANDSHAKE_TRAFFIC_SECRET 6728FCF33C0A58B444672050ADD6EE37372314E521A8648B9982C253F66EC234 53F7A61A89DB9E468B171589D0BA33D1BBEE6C6DB641D2C239F940BEA88B3F4AFBC74162199C8386D42D1A7E4BD7CCF7
SERVER_TRAFFIC_SECRET_0 6728FCF33C0A58B444672050ADD6EE37372314E521A8648B9982C253F66EC234 7CCB3F804F4AECA7E457284B6C70798B62DFC7FC27F0980F0E5719CAF479E8EE1C69369D73AD34A9C7BDF50A3EBE24FE
CLIENT_TRAFFIC_SECRET_0 6728FCF33C0A58B444672050ADD6EE37372314E521A8648B9982C253F66EC234 22CD4F05E25A7EC56CD82FD34D82D266D14B08D26B6DB39110DEEE204A48F461C8D75D2EC77702B675504B4C23F43DED
```

So that's the same secrets you are seeing. `EXPORTER_SECRET` is not used ([see comments](https://security.stackexchange.com/questions/219867/what-are-the-different-secrets-in-the-sslkeylogfile-file)).
What you are describing is the expected behaviour.

Could there be some problem with the wireshark decription? You could try to enable `TLS debug` in [Wireshark settings](https://wiki.wireshark.org/TLS) to get some insight into the decryption process.

**Comment by raboof** [comment]
> So that's the same secrets you are seeing. `EXPORTER_SECRET` is not used ([see comments](https://security.stackexchange.com/questions/219867/what-are-the-different-secrets-in-the-sslkeylogfile-file)).
> What you are describing is the expected behaviour.

Right, and for you wireshark successfully decrypts the traffic? Thanks for confirming!

> Could there be some problem with the wireshark decription? You could try to enable TLS debug in [Wireshark settings](https://wiki.wireshark.org/TLS) to get some insight into the decryption process.

I'll dig there, thanks!

**Comment by neykov** [comment]
> Right, and for you wireshark successfully decrypts the traffic? 

Yeah I am able to decrypt.

If you are able to package some self contained test case that can reproduce the problem I'd be happy to troubleshoot it on my side.

Is the failure to decrypt specific to a particular endpoint?

**Comment by raboof** [comment]
Upon closer inspection, trying again now worked fine! 

At first only the request was properly decoded, but after enabling the TCP "Reassemble out-of-order segments" option I now also see the response.

Sorry for the noise :)

**Comment by neykov** [comment]
Thanks for confirming @raboof. 

I'll close the ticket, as per the above conversation `EXPORTER_SECRET` is not expected to be captured.
