### ISSUE TITLE
Attaching to running process with missing tools.jar

### ISSUE THREAD

**Issue by guerda** [neykov/extract-ssl-secrets#2]
I'm currently trying to attach extract-ssl-secrets to a running Java process. I'm using OpenJDK 12.0.2 and OpenJDK 13.0.2
It is missing the tools.jar, therefore the extract-ssl-secrets does not work.

```
Invalid JAVA_HOME environment variable 'C:\jdk-12.0.2'.
Must point to a local JDK installation containing a 'lib/tools.jar' file.

```
Is there a workaround or a fix for this?

**Comment by neykov** [comment]
@guerda make sure the `java.exe` you are using comes from `C:\jdk-12.0.2`. 

Java 9+ doesn't provide `tools.jar` any longer, but the app will work around it, as long as it is started from a JDK deployment. Seems I need to improve the error message.

To double check the above, I installed a JDK build of OpenJDK 12.0.2 on a clean windows machine and tried using it. I was able to attach without any issues.

**Comment by guerda** [comment]
Hi @neykov !
Thanks for your reply. Indeed this works fine if started from the JDK java binary.

Maybe you can add one line of error message here: https://github.com/neykov/extract-tls-secrets/blob/77b47662a5959b5e1ec6e04c22e73357a637501e/src/main/java/name/neykov/secrets/AgentAttach.java#L116

System.err.println("If you are using JDK > 9, please use the java binary from the JDK.");

**Comment by neykov** [comment]
@guerda wdyt about the error message which I made specific to 9+ installs:
`No access to JDK classes. Make sure to use the java executable from a JDK install.`.

For 8 and lower the original error message is displayed.

**Comment by guerda** [comment]
Looks good, thank you for the addition!
