### ISSUE TITLE
Unable to log down information

### ISSUE THREAD

**Issue by rbk1001** [neykov/extract-ssl-secrets#3]
Hi

I am trying to use the extract-tls-secrets-4.0.0.jar on OpenJDK13, however, I am not able to find any information generated although my java process can be started. Can you advise?

From the log, it looks like the extract-tls-secrets-4.0.0.jar is loaded.

OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
Apr 22, 2020 7:29:54 AM name.neykov.secrets.AgentMain main
INFO: Successfully attached agent /data1/config/extract-tls-secrets-4.0.0.jar. Logging to /data1/logs/secrets.log. 
WARNING: An illegal reflective access operation has occurred

**Comment by neykov** [comment]
Thanks for reporting @rbk1001. 
I wasn't able to reproduce the problem. Can you provide more details.
Is this specific to the java version?
Does it work with other applications?
Anything else you can think of...

**Comment by neykov** [comment]
@rbk1001 unfortunately there's not enough information here to track down the problem. Any additional details would be very useful.
