### ISSUE TITLE
Failed to attach to java process xxxx. Cause: Unable to open socket file: target process not responding or HotSpot VM not loaded

### ISSUE THREAD

**Issue by tonysepia** [neykov/extract-ssl-secrets#4]
Hello, thank you for the software!

Sadly, I am getting the following error:

> Failed to attach to java process xxxx. Cause: Unable to open socket file: target process not responding or HotSpot VM not loaded

What are the pre-requisites for the target process responding? Can I target Glassfish server?

**Comment by neykov** [comment]
Hi @tonysepia. This looks like a permissions related issue. 
Can you try running `jstack` against the process first, making sure it can attach successfully.
Make sure you are running the attach command with the user the glassfish server is running under. Or alternatively with `sudo` rights.

**Comment by tonysepia** [comment]
Hi @neykov ,

I get two different results;

```
jstack -m 11829
Attaching to process ID 11829, please wait...
Debugger attached successfully.
```

```
jstack -l 11829
11829: Unable to open socket file: target process not responding or HotSpot VM not loaded
The -F option can be used when the target process is not responding
```

and with -F

```
jstack -l 11829 -F
Attaching to core -F from executable 11829, please wait...
Error attaching to core file: cannot open binary file
```

**Comment by neykov** [comment]
What's the difference between the two jstack executions, is it just the parameter? 
Make sure that you are executing `jstack`/the extract-tls-secrets agent:
  * with the same JVM
  * same user that is running the glassfish server. (e.x. `sudo -u <glassfish username> jstack 11829`). You can get the glassfish username by looking at the output of `ps aux`.

See the [SO thread](https://stackoverflow.com/questions/7420501/jstack-target-process-not-responding) for further troubleshooting ideas.

If you can't get the attach functionality working reliably in your environment, you can [attach the agent on startup](https://github.com/neykov/extract-tls-secrets#attach-on-startup) instead.

**Comment by tonysepia** [comment]
@neykov Thank you! Adding the `sudo -u` has made the difference!
