### ISSUE TITLE
Cannot decrypt TLS 1.2 with TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 cipher suite selected

### ISSUE THREAD

**Issue by weekendzhang** [neykov/extract-ssl-secrets#5]
the TLS version is 1.2 and the selected cipher suite is TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
The secrets log is like below:
RSA Session-ID: Master-Key:888E59D7EDF19AB2CB6DD704D924E0BAF703B5D998041147D4569D91C0BB5356CD3C694AFCDB2B8ED5CB5CEE1C116D59
RSA Session-ID: Master-Key:E93F8E6EF8A255A6D5BA400233F51C6BAE705CE74E86BBC993180A7DDC9B946FE9125D4F44026A16643264BAD97E7582
RSA Session-ID: Master-Key:BBD7BFBFA0C5000A2CCA2728123188CC3E620911D32DD9896AD068A0E5171D317A270FE860CCF500B524F621DA1CC086
RSA Session-ID: Master-Key:78388503F830251EAFB24BFA17036E99A5A0154E7C0CADB0F22FFC36F7800CB2C609B6BF67F72AF6984360BC8302AD54
RSA Session-ID: Master-Key:E7F59A73F83A76F227DC3581DB58D655BD58223449C4C8B299EC4FBA120C23AC0A6959FB6F5F33510B9A73EA3FABC586
RSA Session-ID: Master-Key:C74452C852514786E15EDD2D9818E3C6804916C0B95929E397A637318F15FE803A1D1F2AB06396C9AA8EF09F1098B6F0

But  the wireshark cannot decrypt the TLS packet.

**Comment by weekendzhang** [comment]
somebody can help me for this?

**Comment by weekendzhang** [comment]
it seems the session-id is not print correctly

**Comment by neykov** [comment]
Let me investigate, thanks for reporting.

**Comment by neykov** [comment]
@weekendzhang I wasn't able to reproduce. Can you give some additional information. For example:
* Java version.
* Do you attach on startup or to a running process.
* Do you capture on the client or server side.
* Attach the output of the process when started with `-Djavax.net.debugg=all`.

**Comment by weekendzhang** [comment]
Thanks for your time.
I try to reproduce, but cannot too, and can get the log file like below
RSA Session-ID:A1327DD27D60DB8E7E487E7FAD52A98CC0B751C95753E6A6352BA8F7C924662F Master-Key:25B055B57A62B202E0C685A12261395CABD99A744BE36239BD47AA57C2689F116915E77B6695E93B89A1B4105743A448
RSA Session-ID:DE9C1540D4EEB3E66564763F536E37DF23D9A474341866AFEB10CB474E56022E Master-Key:7ABA2741974BCF115C153E69CFAA25913A3902B6FB9D2E1A432417AE841C693294695F7A6B8ACEC5202737F04C2FAE41

The session-id is print, if i encountered same issue next time, i will remeber the fixed reproduce steps, sorry for giving you troubles and thanks

**Comment by neykov** [comment]
Thanks @weekendzhang . Feel free to reopen if you are able to reproduce.
