### ISSUE TITLE
attach problem

### ISSUE THREAD

**Issue by 91paZi** [neykov/extract-ssl-secrets#9]
(LINUX) Can someone please guide me how and where to attach the file.. coz am about throw this laptop out the window...
In terminal It tells me <pid> number that i need attach to and when i type the number it says theres no java at this <pid> process then gives me new number... and again and again...
I would be gratefull if someone could save me from a headache

**Comment by gresm** [comment]
If this is:
```
<pid> extract-tls-secrets-<version>.jar list
```
that means you are trying to attach to incorrect process - to the program that you run to list processes, but it finishes after execution the command in terminal. If this is the case, try other process. That is the current one when running the program, but it exists for only the short period of time, and I don't see any case where you would like to attach to it...

**Comment by neykov** [comment]
@gresm can you paste the output of the `list` command.

The following will list all java processes with their process ID. It will include a record for the `extract-tls-secrets` process as well, so there will always be at least one entry. You need the entry that does not correspond tot he `extract-tls-secrets` process.
```
java -jar extract-tls-secrets-<version>.jar list
```

Once you have the process ID (through the list command or from Task Mgr) you can execute the following to attach to the process.
```
java -jar extract-tls-secrets-<version>.jar <pid> /tmp/secrets.log
```

**Comment by gresm** [comment]
```
$ java -jar extract-tls-secrets-4.0.0.jar list
20475 extract-tls-secrets-4.0.0.jar list
```
It lists itself, so maybe @91paZi tries to use that pid?
